version: '3.7'
services:
  mysql-server:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_DATABASE: todo-db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql:rw